### Ordinal Encoder

In [2]:
from sklearn.preprocessing import OrdinalEncoder

#### Sorts Alphabetically not Logically

In [3]:
import pandas as pd

df = pd.DataFrame({
    "Size" : ["Medium","Large","Small","Medium"]
})
df

     Size
0  Medium
1   Large
2   Small
3  Medium

In [4]:
encoder = OrdinalEncoder()
x = encoder.fit_transform(df)
x

array([[1.],
       [0.],
       [2.],
       [1.]])

In [5]:
encoder.categories_

[array(['Large', 'Medium', 'Small'], dtype=object)]

### To specify the order

In [6]:
encoder1 = OrdinalEncoder(
    categories=[["Small","Medium","Large"]]
)

In [7]:
x1 = encoder1.fit_transform(df)
x1

array([[1.],
       [2.],
       [0.],
       [1.]])

## ONE HOT ENCODER

In [8]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [9]:
x = np.array([[1],[2]])
new = OneHotEncoder()
x1 = new.fit_transform(x)
x1

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2 stored elements and shape (2, 2)>

In [10]:
x = np.array([[1],[2],[3],[1]])
new = OneHotEncoder(sparse_output=False)
x1 = new.fit_transform(x)
x1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [11]:
df = pd.DataFrame({
    "age" : [10,20,10,43,34],
    "Name" : ["Rahul","Suresh","migul","sekar","raja"]
})
df

   age    Name
0   10   Rahul
1   20  Suresh
2   10   migul
3   43   sekar
4   34    raja

In [12]:
encoder = OneHotEncoder(sparse_output=False)
x = encoder.fit_transform(df)
x

array([[1., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 1., 0.]])

In [14]:
encoder.get_feature_names_out()

array(['age_10', 'age_20', 'age_34', 'age_43', 'Name_Rahul',
       'Name_Suresh', 'Name_migul', 'Name_raja', 'Name_sekar'],
      dtype=object)

In [16]:
x = encoder.fit_transform(df[['Name']])
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.]])

### Binary classification task

In [17]:
y = ["Yes", "No", "Yes", "No"]

In [18]:
from sklearn.preprocessing import LabelBinarizer

lb = LabelBinarizer()

y1 = lb.fit_transform(y)

print(y1)

[[1]
 [0]
 [1]
 [0]]

In [19]:
y = ["Cat", "Dog", "Bird", "Dog"]

In [20]:
lb = LabelBinarizer()

print(lb.fit_transform(y))

[[0 1 0]
 [0 0 1]
 [1 0 0]
 [0 0 1]]

### Add Dummy features

In [21]:
from sklearn.preprocessing import add_dummy_feature

In [22]:
x = np.array([
    [20,10],[30,54],[4,81]
])
x

array([[20, 10],
       [30, 54],
       [ 4, 81]])

In [25]:
x_new = add_dummy_feature(x)
x_new

array([[ 1., 20., 10.],
       [ 1., 30., 54.],
       [ 1.,  4., 81.]])

In [26]:
x_new = add_dummy_feature(x,value=10)
x_new

array([[10., 20., 10.],
       [10., 30., 54.],
       [10.,  4., 81.]])