## Imputation in sklearn

In [1]:
import numpy as np
import pandas as pd

df = pd.DataFrame({
    "Age": [20, 25, np.nan, 35, 40],
    "Salary": [30000, np.nan, 50000, 60000, 70000]
})

df

    Age   Salary
0  20.0  30000.0
1  25.0      NaN
2   NaN  50000.0
3  35.0  60000.0
4  40.0  70000.0

In [2]:
from sklearn.impute import SimpleImputer

#### By default fit_transform() converts DataFrame into Numpy array

In [3]:
imputer1 = SimpleImputer(strategy="mean")
x1 = imputer1.fit_transform(df)
x1

array([[2.00e+01, 3.00e+04],
       [2.50e+01, 5.25e+04],
       [3.00e+01, 5.00e+04],
       [3.50e+01, 6.00e+04],
       [4.00e+01, 7.00e+04]])

#### Use Mean when there are no strong outliers, use Median when there is a skewed distribution

In [ ]:
imputer2 = SimpleImputer(strategy="median")

x2 = imputer2.fit_transform(df)
x2

array([[2.0e+01, 3.0e+04],
       [2.5e+01, 5.5e+04],
       [3.0e+01, 5.0e+04],
       [3.5e+01, 6.0e+04],
       [4.0e+01, 7.0e+04]])

In [6]:
imputer3 = SimpleImputer(strategy="constant",fill_value=0)
x3 = imputer3.fit_transform(df)
x3

array([[2.0e+01, 3.0e+04],
       [2.5e+01, 0.0e+00],
       [0.0e+00, 5.0e+04],
       [3.5e+01, 6.0e+04],
       [4.0e+01, 7.0e+04]])

#### One imputer with strategy="constant" uses the same fill_value for all columns it transforms.

#### individual columns are handled by individual imputers

In [7]:
age_imputer = SimpleImputer(strategy="constant", fill_value=0)
salary_imputer = SimpleImputer(strategy="constant", fill_value=10000)

df[["Age"]] = age_imputer.fit_transform(df[["Age"]])
df[["Salary"]] = salary_imputer.fit_transform(df[["Salary"]])

In [8]:
df["Age"]

0    20.0
1    25.0
2     0.0
3    35.0
4    40.0
Name: Age, dtype: float64

In [9]:
df['Salary']

0    30000.0
1    10000.0
2    50000.0
3    60000.0
4    70000.0
Name: Salary, dtype: float64

## KNN IMPUTER

In [10]:
df = pd.DataFrame({
    "Age":    [20, 22, 40, 42, 21],
    "Salary": [30000, 32000, 80000, 85000, np.nan]
})
df

   Age   Salary
0   20  30000.0
1   22  32000.0
2   40  80000.0
3   42  85000.0
4   21      NaN

In [11]:
from sklearn.impute import KNNImputer

imputer = KNNImputer(n_neighbors=2)

X = imputer.fit_transform(df)

X

array([[2.0e+01, 3.0e+04],
       [2.2e+01, 3.2e+04],
       [4.0e+01, 8.0e+04],
       [4.2e+01, 8.5e+04],
       [2.1e+01, 3.1e+04]])